---
# further condition the pis with updates and necessary packages
- hosts: polar_all
  gather_facts: false
  become: yes

  # vars_files:
  #   - vars.yaml
  
  tasks:
    - name: update apt cache and the system
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes
    
    # we don't need ntp so skip this step
    # since ubuntu 16.04 it's using timedatectl / timesyncd instead, work out of the box
    # - name: install packages
    #   apt:
    #     pkg:
    #       - ntp

    - name: set time zone
      timezone:
        name: America/Los_Angeles

    # - name: reboot unconditionally
    #   reboot:

    # - name: check if reboot if required
    #   shell: sleep 5 && shutdown -r now 'Reboot after updates from Ansible'
    #   args:
    #     removes : /var/run/reboot-required