---
# further condition the pis with updates and necessary packages
- hosts: polar-all
  become: yes

  vars_files:
    - vars.yaml
  
  tasks:
    - name: update apt cache and the system
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes
    
    - name: install packages
      apt:
        pkg:
          - ntp

    - name: set time zone
      timezone:
        name: America/Los_Angeles

    - name: reboot if required
      shell: "sleep 10; /usr/sbin/reboot"
      args:
        removes: /var/run/reboot-erquired
      async: 300
      poll: 0
      ignore_errors: true