---
# further condition the pis with updates and necessary packages
- hosts: polar-all
  gather_facts: false
  become: yes

  # vars_files:
  #   - vars.yaml
  
  tasks:
    - name: update apt cache and the system
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes
    
    # we don't need ntp so skip this step
    # since ubuntu 16.04 it's using timedatectl / timesyncd instead, work out of the box
    # - name: install packages
    #   apt:
    #     pkg:
    #       - ntp

    - name: set time zone
      timezone:
        name: America/Los_Angeles

    - name: reboot if required
      shell: "sleep 10; /usr/sbin/reboot"
      args:
        removes: /var/run/reboot-erquired
      async: 300
      poll: 0
      ignore_errors: true