---
# further condition the pis with updates and necessary packages
- hosts: all
  become: yes

  vars_files:
    - vars.yaml
  
  tasks:
    - name: update apt cache and the system
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes
    
    - name: install packages
      apt:
        pkg:
          - ntp

    - name: set time zone
      timezone:
        name: America/Los_Angeles