---
# shutdown all hosts
- hosts: polar-all
  become: yes

  tasks:
  # - name: reboot host with command-shutdown module
  #   command: "/sbin/shutdown -r +1"
  #   async: 0
  #   poll: 0
  #   ignore_errors: yes

  - name: reboot host unconditionally
    reboot: