---
# shutdown all hosts
- hosts: polar_all
  gather_facts: no
  become: yes

  tasks:
  - name: shutdown hosts
    command: "/sbin/shutdown -h +1"
    poll: 0
    async: 0
    ignore_errors: yes
    
